DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS contents;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role INTEGER NOT NULL
);

CREATE TABLE contents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  access_level INTEGER NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL
);
